### PR TITLE
Adding missing user defined primitives.

### PR DESCRIPTION
**Pull request by mithro**
Signed-off-by: Tim 'mithro' Ansell <tansell@google.com>

### CODE REVIEW

**Review by QuantamHD — APPROVED** [review]
Lgtm

**Review by RTimothyEdwards — APPROVED** [review]
Expected equivalent update for the 9-track library as for the 7-track library.  Looks good to me.

**Comment by mithro** [comment]
You mean the one at https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_sc_mcu7t5v0/pull/27 you already looked at? :-P

**Comment by RTimothyEdwards** [comment]
What I meant was that "this is the equivalent update that I was expecting".  Poorly phrased.

**Pull request merged**
